version: '3.8'

services:
  ssh-server:
    build: .
    ports:
      - "2222:22"
    container_name: ssh-test-server
    volumes:
      - ./tests/tests_files:/root/remote_files  # Mount test_files here