name: Run tests and compute coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install project with dependencies from pyproject.toml
        run: |
          python -m pip install --upgrade pip
          pip install .  # installs pyalma package with dependencies from pyproject.toml
          pip install coverage pytest pytest-mock  # explicitly install test tools


      - name: Run tests with coverage
        run: |
          coverage run -m pytest --ignore=tests/integration
          coverage report
          coverage xml

